apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - prometheus-rbac.yaml
  - prometheus-config.yaml
  - prometheus-deployment.yaml
  - godel-services.yaml
