//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 The Godel Scheduler Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	config "github.com/kubewharf/godel-scheduler/pkg/scheduler/apis/config"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GodelSchedulerConfiguration) DeepCopyInto(out *GodelSchedulerConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.LeaderElection.DeepCopyInto(&out.LeaderElection)
	out.ClientConnection = in.ClientConnection
	in.DebuggingConfiguration.DeepCopyInto(&out.DebuggingConfiguration)
	if in.SchedulerName != nil {
		in, out := &in.SchedulerName, &out.SchedulerName
		*out = new(string)
		**out = **in
	}
	if in.SubClusterKey != nil {
		in, out := &in.SubClusterKey, &out.SubClusterKey
		*out = new(string)
		**out = **in
	}
	if in.Tracer != nil {
		in, out := &in.Tracer, &out.Tracer
		*out = (*in).DeepCopy()
	}
	if in.DefaultProfile != nil {
		in, out := &in.DefaultProfile, &out.DefaultProfile
		*out = new(GodelSchedulerProfile)
		(*in).DeepCopyInto(*out)
	}
	if in.SubClusterProfiles != nil {
		in, out := &in.SubClusterProfiles, &out.SubClusterProfiles
		*out = make([]GodelSchedulerProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GodelSchedulerConfiguration.
func (in *GodelSchedulerConfiguration) DeepCopy() *GodelSchedulerConfiguration {
	if in == nil {
		return nil
	}
	out := new(GodelSchedulerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GodelSchedulerConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GodelSchedulerProfile) DeepCopyInto(out *GodelSchedulerProfile) {
	*out = *in
	if in.BasePluginsForKubelet != nil {
		in, out := &in.BasePluginsForKubelet, &out.BasePluginsForKubelet
		*out = new(config.Plugins)
		(*in).DeepCopyInto(*out)
	}
	if in.BasePluginsForNM != nil {
		in, out := &in.BasePluginsForNM, &out.BasePluginsForNM
		*out = new(config.Plugins)
		(*in).DeepCopyInto(*out)
	}
	if in.PluginConfigs != nil {
		in, out := &in.PluginConfigs, &out.PluginConfigs
		*out = make([]config.PluginConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PreemptionPluginConfigs != nil {
		in, out := &in.PreemptionPluginConfigs, &out.PreemptionPluginConfigs
		*out = make([]config.PluginConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PercentageOfNodesToScore != nil {
		in, out := &in.PercentageOfNodesToScore, &out.PercentageOfNodesToScore
		*out = new(int32)
		**out = **in
	}
	if in.IncreasedPercentageOfNodesToScore != nil {
		in, out := &in.IncreasedPercentageOfNodesToScore, &out.IncreasedPercentageOfNodesToScore
		*out = new(int32)
		**out = **in
	}
	if in.DisablePreemption != nil {
		in, out := &in.DisablePreemption, &out.DisablePreemption
		*out = new(bool)
		**out = **in
	}
	if in.BlockQueue != nil {
		in, out := &in.BlockQueue, &out.BlockQueue
		*out = new(bool)
		**out = **in
	}
	if in.UnitQueueSortPlugin != nil {
		in, out := &in.UnitQueueSortPlugin, &out.UnitQueueSortPlugin
		*out = new(config.Plugin)
		**out = **in
	}
	if in.AttemptImpactFactorOnPriority != nil {
		in, out := &in.AttemptImpactFactorOnPriority, &out.AttemptImpactFactorOnPriority
		*out = new(float64)
		**out = **in
	}
	if in.UnitInitialBackoffSeconds != nil {
		in, out := &in.UnitInitialBackoffSeconds, &out.UnitInitialBackoffSeconds
		*out = new(int64)
		**out = **in
	}
	if in.UnitMaxBackoffSeconds != nil {
		in, out := &in.UnitMaxBackoffSeconds, &out.UnitMaxBackoffSeconds
		*out = new(int64)
		**out = **in
	}
	if in.CandidatesSelectPolicy != nil {
		in, out := &in.CandidatesSelectPolicy, &out.CandidatesSelectPolicy
		*out = new(string)
		**out = **in
	}
	if in.BetterSelectPolicies != nil {
		in, out := &in.BetterSelectPolicies, &out.BetterSelectPolicies
		*out = new(config.StringSlice)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GodelSchedulerProfile.
func (in *GodelSchedulerProfile) DeepCopy() *GodelSchedulerProfile {
	if in == nil {
		return nil
	}
	out := new(GodelSchedulerProfile)
	in.DeepCopyInto(out)
	return out
}
