//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 The Godel Scheduler Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	config "github.com/kubewharf/godel-scheduler/pkg/binder/apis/config"
	tracing "github.com/kubewharf/godel-scheduler/pkg/util/tracing"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*GodelBinderConfiguration)(nil), (*config.GodelBinderConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_GodelBinderConfiguration_To_config_GodelBinderConfiguration(a.(*GodelBinderConfiguration), b.(*config.GodelBinderConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.GodelBinderConfiguration)(nil), (*GodelBinderConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_GodelBinderConfiguration_To_v1beta1_GodelBinderConfiguration(a.(*config.GodelBinderConfiguration), b.(*GodelBinderConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GodelBinderProfile)(nil), (*config.GodelBinderProfile)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_GodelBinderProfile_To_config_GodelBinderProfile(a.(*GodelBinderProfile), b.(*config.GodelBinderProfile), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.GodelBinderProfile)(nil), (*GodelBinderProfile)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_GodelBinderProfile_To_v1beta1_GodelBinderProfile(a.(*config.GodelBinderProfile), b.(*GodelBinderProfile), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Plugin)(nil), (*config.Plugin)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Plugin_To_config_Plugin(a.(*Plugin), b.(*config.Plugin), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Plugin)(nil), (*Plugin)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Plugin_To_v1beta1_Plugin(a.(*config.Plugin), b.(*Plugin), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PluginConfig)(nil), (*config.PluginConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PluginConfig_To_config_PluginConfig(a.(*PluginConfig), b.(*config.PluginConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.PluginConfig)(nil), (*PluginConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_PluginConfig_To_v1beta1_PluginConfig(a.(*config.PluginConfig), b.(*PluginConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Plugins)(nil), (*config.Plugins)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Plugins_To_config_Plugins(a.(*Plugins), b.(*config.Plugins), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Plugins)(nil), (*Plugins)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Plugins_To_v1beta1_Plugins(a.(*config.Plugins), b.(*Plugins), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VictimCheckingPluginCollection)(nil), (*config.VictimCheckingPluginCollection)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VictimCheckingPluginCollection_To_config_VictimCheckingPluginCollection(a.(*VictimCheckingPluginCollection), b.(*config.VictimCheckingPluginCollection), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.VictimCheckingPluginCollection)(nil), (*VictimCheckingPluginCollection)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_VictimCheckingPluginCollection_To_v1beta1_VictimCheckingPluginCollection(a.(*config.VictimCheckingPluginCollection), b.(*VictimCheckingPluginCollection), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VictimCheckingPluginSet)(nil), (*config.VictimCheckingPluginSet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VictimCheckingPluginSet_To_config_VictimCheckingPluginSet(a.(*VictimCheckingPluginSet), b.(*config.VictimCheckingPluginSet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.VictimCheckingPluginSet)(nil), (*VictimCheckingPluginSet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_VictimCheckingPluginSet_To_v1beta1_VictimCheckingPluginSet(a.(*config.VictimCheckingPluginSet), b.(*VictimCheckingPluginSet), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_GodelBinderConfiguration_To_config_GodelBinderConfiguration(in *GodelBinderConfiguration, out *config.GodelBinderConfiguration, s conversion.Scope) error {
	out.DebuggingConfiguration = in.DebuggingConfiguration
	out.ClientConnection = in.ClientConnection
	out.SchedulerName = (*string)(unsafe.Pointer(in.SchedulerName))
	out.LeaderElection = in.LeaderElection
	out.HealthzBindAddress = in.HealthzBindAddress
	out.MetricsBindAddress = in.MetricsBindAddress
	out.VolumeBindingTimeoutSeconds = in.VolumeBindingTimeoutSeconds
	out.Tracer = (*tracing.TracerConfiguration)(unsafe.Pointer(in.Tracer))
	out.ReservationTimeOutSeconds = in.ReservationTimeOutSeconds
	out.Profile = (*config.GodelBinderProfile)(unsafe.Pointer(in.Profile))
	return nil
}

// Convert_v1beta1_GodelBinderConfiguration_To_config_GodelBinderConfiguration is an autogenerated conversion function.
func Convert_v1beta1_GodelBinderConfiguration_To_config_GodelBinderConfiguration(in *GodelBinderConfiguration, out *config.GodelBinderConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta1_GodelBinderConfiguration_To_config_GodelBinderConfiguration(in, out, s)
}

func autoConvert_config_GodelBinderConfiguration_To_v1beta1_GodelBinderConfiguration(in *config.GodelBinderConfiguration, out *GodelBinderConfiguration, s conversion.Scope) error {
	out.DebuggingConfiguration = in.DebuggingConfiguration
	out.ClientConnection = in.ClientConnection
	out.SchedulerName = (*string)(unsafe.Pointer(in.SchedulerName))
	out.LeaderElection = in.LeaderElection
	out.HealthzBindAddress = in.HealthzBindAddress
	out.MetricsBindAddress = in.MetricsBindAddress
	out.VolumeBindingTimeoutSeconds = in.VolumeBindingTimeoutSeconds
	out.Tracer = (*tracing.TracerConfiguration)(unsafe.Pointer(in.Tracer))
	out.ReservationTimeOutSeconds = in.ReservationTimeOutSeconds
	out.Profile = (*GodelBinderProfile)(unsafe.Pointer(in.Profile))
	return nil
}

// Convert_config_GodelBinderConfiguration_To_v1beta1_GodelBinderConfiguration is an autogenerated conversion function.
func Convert_config_GodelBinderConfiguration_To_v1beta1_GodelBinderConfiguration(in *config.GodelBinderConfiguration, out *GodelBinderConfiguration, s conversion.Scope) error {
	return autoConvert_config_GodelBinderConfiguration_To_v1beta1_GodelBinderConfiguration(in, out, s)
}

func autoConvert_v1beta1_GodelBinderProfile_To_config_GodelBinderProfile(in *GodelBinderProfile, out *config.GodelBinderProfile, s conversion.Scope) error {
	out.Plugins = (*config.Plugins)(unsafe.Pointer(in.Plugins))
	out.PreemptionPluginConfigs = *(*[]config.PluginConfig)(unsafe.Pointer(&in.PreemptionPluginConfigs))
	out.PluginConfigs = *(*[]config.PluginConfig)(unsafe.Pointer(&in.PluginConfigs))
	return nil
}

// Convert_v1beta1_GodelBinderProfile_To_config_GodelBinderProfile is an autogenerated conversion function.
func Convert_v1beta1_GodelBinderProfile_To_config_GodelBinderProfile(in *GodelBinderProfile, out *config.GodelBinderProfile, s conversion.Scope) error {
	return autoConvert_v1beta1_GodelBinderProfile_To_config_GodelBinderProfile(in, out, s)
}

func autoConvert_config_GodelBinderProfile_To_v1beta1_GodelBinderProfile(in *config.GodelBinderProfile, out *GodelBinderProfile, s conversion.Scope) error {
	out.Plugins = (*Plugins)(unsafe.Pointer(in.Plugins))
	out.PreemptionPluginConfigs = *(*[]PluginConfig)(unsafe.Pointer(&in.PreemptionPluginConfigs))
	out.PluginConfigs = *(*[]PluginConfig)(unsafe.Pointer(&in.PluginConfigs))
	return nil
}

// Convert_config_GodelBinderProfile_To_v1beta1_GodelBinderProfile is an autogenerated conversion function.
func Convert_config_GodelBinderProfile_To_v1beta1_GodelBinderProfile(in *config.GodelBinderProfile, out *GodelBinderProfile, s conversion.Scope) error {
	return autoConvert_config_GodelBinderProfile_To_v1beta1_GodelBinderProfile(in, out, s)
}

func autoConvert_v1beta1_Plugin_To_config_Plugin(in *Plugin, out *config.Plugin, s conversion.Scope) error {
	out.Name = in.Name
	out.Weight = in.Weight
	return nil
}

// Convert_v1beta1_Plugin_To_config_Plugin is an autogenerated conversion function.
func Convert_v1beta1_Plugin_To_config_Plugin(in *Plugin, out *config.Plugin, s conversion.Scope) error {
	return autoConvert_v1beta1_Plugin_To_config_Plugin(in, out, s)
}

func autoConvert_config_Plugin_To_v1beta1_Plugin(in *config.Plugin, out *Plugin, s conversion.Scope) error {
	out.Name = in.Name
	out.Weight = in.Weight
	return nil
}

// Convert_config_Plugin_To_v1beta1_Plugin is an autogenerated conversion function.
func Convert_config_Plugin_To_v1beta1_Plugin(in *config.Plugin, out *Plugin, s conversion.Scope) error {
	return autoConvert_config_Plugin_To_v1beta1_Plugin(in, out, s)
}

func autoConvert_v1beta1_PluginConfig_To_config_PluginConfig(in *PluginConfig, out *config.PluginConfig, s conversion.Scope) error {
	out.Name = in.Name
	out.Args = in.Args
	return nil
}

// Convert_v1beta1_PluginConfig_To_config_PluginConfig is an autogenerated conversion function.
func Convert_v1beta1_PluginConfig_To_config_PluginConfig(in *PluginConfig, out *config.PluginConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_PluginConfig_To_config_PluginConfig(in, out, s)
}

func autoConvert_config_PluginConfig_To_v1beta1_PluginConfig(in *config.PluginConfig, out *PluginConfig, s conversion.Scope) error {
	out.Name = in.Name
	out.Args = in.Args
	return nil
}

// Convert_config_PluginConfig_To_v1beta1_PluginConfig is an autogenerated conversion function.
func Convert_config_PluginConfig_To_v1beta1_PluginConfig(in *config.PluginConfig, out *PluginConfig, s conversion.Scope) error {
	return autoConvert_config_PluginConfig_To_v1beta1_PluginConfig(in, out, s)
}

func autoConvert_v1beta1_Plugins_To_config_Plugins(in *Plugins, out *config.Plugins, s conversion.Scope) error {
	out.VictimChecking = (*config.VictimCheckingPluginSet)(unsafe.Pointer(in.VictimChecking))
	return nil
}

// Convert_v1beta1_Plugins_To_config_Plugins is an autogenerated conversion function.
func Convert_v1beta1_Plugins_To_config_Plugins(in *Plugins, out *config.Plugins, s conversion.Scope) error {
	return autoConvert_v1beta1_Plugins_To_config_Plugins(in, out, s)
}

func autoConvert_config_Plugins_To_v1beta1_Plugins(in *config.Plugins, out *Plugins, s conversion.Scope) error {
	out.VictimChecking = (*VictimCheckingPluginSet)(unsafe.Pointer(in.VictimChecking))
	return nil
}

// Convert_config_Plugins_To_v1beta1_Plugins is an autogenerated conversion function.
func Convert_config_Plugins_To_v1beta1_Plugins(in *config.Plugins, out *Plugins, s conversion.Scope) error {
	return autoConvert_config_Plugins_To_v1beta1_Plugins(in, out, s)
}

func autoConvert_v1beta1_VictimCheckingPluginCollection_To_config_VictimCheckingPluginCollection(in *VictimCheckingPluginCollection, out *config.VictimCheckingPluginCollection, s conversion.Scope) error {
	out.ForceQuickPass = in.ForceQuickPass
	out.EnableQuickPass = in.EnableQuickPass
	out.Plugins = *(*[]config.Plugin)(unsafe.Pointer(&in.Plugins))
	return nil
}

// Convert_v1beta1_VictimCheckingPluginCollection_To_config_VictimCheckingPluginCollection is an autogenerated conversion function.
func Convert_v1beta1_VictimCheckingPluginCollection_To_config_VictimCheckingPluginCollection(in *VictimCheckingPluginCollection, out *config.VictimCheckingPluginCollection, s conversion.Scope) error {
	return autoConvert_v1beta1_VictimCheckingPluginCollection_To_config_VictimCheckingPluginCollection(in, out, s)
}

func autoConvert_config_VictimCheckingPluginCollection_To_v1beta1_VictimCheckingPluginCollection(in *config.VictimCheckingPluginCollection, out *VictimCheckingPluginCollection, s conversion.Scope) error {
	out.ForceQuickPass = in.ForceQuickPass
	out.EnableQuickPass = in.EnableQuickPass
	out.Plugins = *(*[]Plugin)(unsafe.Pointer(&in.Plugins))
	return nil
}

// Convert_config_VictimCheckingPluginCollection_To_v1beta1_VictimCheckingPluginCollection is an autogenerated conversion function.
func Convert_config_VictimCheckingPluginCollection_To_v1beta1_VictimCheckingPluginCollection(in *config.VictimCheckingPluginCollection, out *VictimCheckingPluginCollection, s conversion.Scope) error {
	return autoConvert_config_VictimCheckingPluginCollection_To_v1beta1_VictimCheckingPluginCollection(in, out, s)
}

func autoConvert_v1beta1_VictimCheckingPluginSet_To_config_VictimCheckingPluginSet(in *VictimCheckingPluginSet, out *config.VictimCheckingPluginSet, s conversion.Scope) error {
	out.PluginCollections = *(*[]config.VictimCheckingPluginCollection)(unsafe.Pointer(&in.PluginCollections))
	return nil
}

// Convert_v1beta1_VictimCheckingPluginSet_To_config_VictimCheckingPluginSet is an autogenerated conversion function.
func Convert_v1beta1_VictimCheckingPluginSet_To_config_VictimCheckingPluginSet(in *VictimCheckingPluginSet, out *config.VictimCheckingPluginSet, s conversion.Scope) error {
	return autoConvert_v1beta1_VictimCheckingPluginSet_To_config_VictimCheckingPluginSet(in, out, s)
}

func autoConvert_config_VictimCheckingPluginSet_To_v1beta1_VictimCheckingPluginSet(in *config.VictimCheckingPluginSet, out *VictimCheckingPluginSet, s conversion.Scope) error {
	out.PluginCollections = *(*[]VictimCheckingPluginCollection)(unsafe.Pointer(&in.PluginCollections))
	return nil
}

// Convert_config_VictimCheckingPluginSet_To_v1beta1_VictimCheckingPluginSet is an autogenerated conversion function.
func Convert_config_VictimCheckingPluginSet_To_v1beta1_VictimCheckingPluginSet(in *config.VictimCheckingPluginSet, out *VictimCheckingPluginSet, s conversion.Scope) error {
	return autoConvert_config_VictimCheckingPluginSet_To_v1beta1_VictimCheckingPluginSet(in, out, s)
}
