//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 The Godel Scheduler Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GodelBinderConfiguration) DeepCopyInto(out *GodelBinderConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.DebuggingConfiguration.DeepCopyInto(&out.DebuggingConfiguration)
	out.ClientConnection = in.ClientConnection
	if in.SchedulerName != nil {
		in, out := &in.SchedulerName, &out.SchedulerName
		*out = new(string)
		**out = **in
	}
	in.LeaderElection.DeepCopyInto(&out.LeaderElection)
	if in.Tracer != nil {
		in, out := &in.Tracer, &out.Tracer
		*out = (*in).DeepCopy()
	}
	if in.Profile != nil {
		in, out := &in.Profile, &out.Profile
		*out = new(GodelBinderProfile)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GodelBinderConfiguration.
func (in *GodelBinderConfiguration) DeepCopy() *GodelBinderConfiguration {
	if in == nil {
		return nil
	}
	out := new(GodelBinderConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GodelBinderConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GodelBinderProfile) DeepCopyInto(out *GodelBinderProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = new(Plugins)
		(*in).DeepCopyInto(*out)
	}
	if in.PreemptionPluginConfigs != nil {
		in, out := &in.PreemptionPluginConfigs, &out.PreemptionPluginConfigs
		*out = make([]PluginConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PluginConfigs != nil {
		in, out := &in.PluginConfigs, &out.PluginConfigs
		*out = make([]PluginConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GodelBinderProfile.
func (in *GodelBinderProfile) DeepCopy() *GodelBinderProfile {
	if in == nil {
		return nil
	}
	out := new(GodelBinderProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GodelBinderProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Plugin) DeepCopyInto(out *Plugin) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Plugin.
func (in *Plugin) DeepCopy() *Plugin {
	if in == nil {
		return nil
	}
	out := new(Plugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginConfig) DeepCopyInto(out *PluginConfig) {
	*out = *in
	in.Args.DeepCopyInto(&out.Args)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginConfig.
func (in *PluginConfig) DeepCopy() *PluginConfig {
	if in == nil {
		return nil
	}
	out := new(PluginConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Plugins) DeepCopyInto(out *Plugins) {
	*out = *in
	if in.VictimChecking != nil {
		in, out := &in.VictimChecking, &out.VictimChecking
		*out = new(VictimCheckingPluginSet)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Plugins.
func (in *Plugins) DeepCopy() *Plugins {
	if in == nil {
		return nil
	}
	out := new(Plugins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VictimCheckingPluginCollection) DeepCopyInto(out *VictimCheckingPluginCollection) {
	*out = *in
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]Plugin, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VictimCheckingPluginCollection.
func (in *VictimCheckingPluginCollection) DeepCopy() *VictimCheckingPluginCollection {
	if in == nil {
		return nil
	}
	out := new(VictimCheckingPluginCollection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VictimCheckingPluginSet) DeepCopyInto(out *VictimCheckingPluginSet) {
	*out = *in
	if in.PluginCollections != nil {
		in, out := &in.PluginCollections, &out.PluginCollections
		*out = make([]VictimCheckingPluginCollection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VictimCheckingPluginSet.
func (in *VictimCheckingPluginSet) DeepCopy() *VictimCheckingPluginSet {
	if in == nil {
		return nil
	}
	out := new(VictimCheckingPluginSet)
	in.DeepCopyInto(out)
	return out
}
